name       : ffmpeg
homepage   : https://www.ffmpeg.org/
version    : 3.3.2
release    : 35
source     :
    - https://ffmpeg.org/releases/ffmpeg-3.3.2.tar.xz : 1998de1ab32616cbf2ff86efc3f1f26e76805ec5dc51e24c041c79edd8262785
license    :
    - LGPL-3.0
    - GPL-3.0
component  : multimedia.codecs
summary    : A complete, cross-platform solution to record, convert and stream audio and video.
description: |
    FFmpeg is a multimedia framework, able to decode, encode, transcode, mux, demux,
    stream, filter and play several formats that humans and machines have created.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(caca)
    - pkgconfig(fdk-aac)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(sdl2)
    - pkgconfig(snappy)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - pkgconfig(zimg)
    - lame-devel
    - libgcrypt-devel
    - xvidcore-devel
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    ./configure --prefix=/usr \
        --libdir=%libdir% \
        --disable-debug \
        --disable-stripping \
        --enable-shared \
        --disable-static \
        --enable-avisynth \
        --enable-avresample \
        --enable-gcrypt \
        --enable-gnutls \
        --enable-gpl \
        --enable-libass \
        --enable-libbluray \
        --enable-libcaca \
        --enable-libcdio \
        --enable-libfdk-aac \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libfribidi \
        --enable-libmp3lame \
        --enable-libopus \
        --enable-libpulse \
        --enable-libsnappy \
        --enable-libspeex \
        --enable-libssh \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libv4l2 \
        --enable-libvorbis \
        --enable-libvpx \
        --enable-libwebp \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxvid \
        --enable-libzimg \
        --enable-nonfree \
        --enable-openal \
        --enable-opengl \
        --enable-openssl \
        --enable-sdl2 \
        --enable-version3
build      : |
    %make
install    : |
    %make_install
