name       : ffmpeg
homepage   : https://www.ffmpeg.org/
version    : 4.2.2
release    : 82
source     :
    - https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.xz : cb754255ab0ee2ea5f66f8850e1bd6ad5cac1cd855d0a2f4990fb8c668b0d29c
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : multimedia.codecs
summary    : A complete, cross-platform solution to record, convert and stream audio and video
description: |
    FFmpeg is a multimedia framework, able to decode, encode, transcode, mux, demux, stream, filter and play several formats that humans and machines have created.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aom)
    - pkgconfig(caca)
    - pkgconfig(dav1d)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libdrm)
    - pkgconfig(libgcrypt)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(sdl2)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - pkgconfig(zimg)
    - bzip2-devel
    - lame-devel
    - snappy-devel
    - xvidcore-devel
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    %patch -p1 < $pkgfiles/make-libdav1d-the-preferred-AV1-decoder.patch

    ./configure \
        --enable-avisynth \
        --enable-avresample \
        --enable-gcrypt \
        --enable-gnutls \
        --enable-gpl \
        --enable-libaom \
        --enable-libass \
        --enable-libbluray \
        --enable-libcaca \
        --enable-libcdio \
        --enable-libdav1d \
        --enable-libdrm \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libfribidi \
        --enable-libmp3lame \
        --enable-libopus \
        --enable-libpulse \
        --enable-libsnappy \
        --enable-libspeex \
        --enable-libssh \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libv4l2 \
        --enable-libvorbis \
        --enable-libvpx \
        --enable-libwebp \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxvid \
        --enable-libzimg \
        --enable-nvdec \
        --enable-nvenc \
        --enable-openal \
        --enable-opengl \
        --enable-sdl2 \
        --enable-shared \
        --enable-version3 \
        --disable-debug \
        --disable-static \
        --disable-stripping \
        --libdir=%libdir% \
        --prefix=/usr
build      : |
    %make
install    : |
    %make_install
