name       : ffmpeg
homepage   : https://www.ffmpeg.org/
version    : 4.4.1
release    : 121
source     :
    - https://ffmpeg.org/releases/ffmpeg-4.4.1.tar.xz : eadbad9e9ab30b25f5520fbfde99fae4a92a1ae3c0257a8d68569a4651e30e02
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : multimedia.codecs
summary    : A complete, cross-platform solution to record, convert and stream audio and video
description: |
    FFmpeg is a multimedia framework, able to decode, encode, transcode, mux, demux, stream, filter and play several formats that humans and machines have created.
libsplit   : no
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(alsa)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libdrm)
    - pkgconfig(libgcrypt)
    - pkgconfig(libopenjp2)
    - pkgconfig(libopenmpt)
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(rav1e)
    - pkgconfig(rubberband)
    - pkgconfig(sdl2)
    - pkgconfig(smbclient)
    - pkgconfig(soxr)
    - pkgconfig(speex)
    - pkgconfig(srt)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vpx)
    - pkgconfig(vulkan)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - pkgconfig(zimg)
    - bzip2-devel
    - glslang-devel
    - lame-devel
    - snappy-devel
    - vulkan-headers
    - xvidcore-devel
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    ./configure \
        --enable-avresample \
        --enable-gcrypt \
        --enable-gnutls \
        --enable-gpl \
        --enable-libaom \
        --enable-libass \
        --enable-libbluray \
        --enable-libcdio \
        --enable-libdav1d \
        --enable-libdrm \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libfribidi \
        --enable-libglslang \
        --enable-libmp3lame \
        --enable-libopenjpeg \
        --enable-libopenmpt \
        --enable-libopus \
        --enable-libpulse \
        --enable-librav1e \
        --enable-librubberband \
        --enable-libsmbclient \
        --enable-libsnappy \
        --enable-libsoxr \
        --enable-libspeex \
        --enable-libsrt \
        --enable-libssh \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libv4l2 \
        --enable-libvorbis \
        --enable-libvpx \
        --enable-libwebp \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxvid \
        --enable-libzimg \
        --enable-nvdec \
        --enable-nvenc \
        --enable-openal \
        --enable-opengl \
        --enable-sdl2 \
        --enable-shared \
        --enable-version3 \
        --enable-vulkan \
        --disable-debug \
        --disable-static \
        --disable-stripping \
        --libdir=%libdir% \
        --prefix=/usr
build      : |
    %make
install    : |
    %make_install
