name       : ffmpeg
homepage   : https://www.ffmpeg.org/
version    : 2.8.11
release    : 31
source     :
    - http://ffmpeg.org/releases/ffmpeg-2.8.11.tar.xz : 38aa3aec93c480b34d33f3648aff9278581d151488b521995c084258613e1fe6
license    : LGPL-3.0
component  : multimedia.codecs
summary    : A complete, cross-platform solution to record, convert and stream audio
    and video.
description: |
    A complete, cross-platform solution to record, convert and stream audio and video.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(ogg)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(sdl)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x11)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - faac-devel
    - lame-devel
    - xvidcore-devel
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    # Revisit to enable All The Things
    ./configure --prefix=/usr \
        --libdir=%libdir% \
        --enable-shared \
        --disable-static \
        --enable-avisynth \
        --enable-avresample \
        --enable-gnutls \
        --enable-gpl \
        --enable-libass \
        --enable-libbluray \
        --enable-libfaac \
        --enable-libfreetype \
        --enable-libmp3lame \
        --enable-libopus \
        --enable-libpulse \
        --enable-libspeex \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libv4l2 \
        --enable-libvorbis \
        --enable-libvpx \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxvid \
        --enable-nonfree \
        --enable-opengl \
        --enable-openssl \
        --enable-vaapi \
        --enable-vdpau \
        --enable-version3 \
        --enable-x11grab
build      : |
    %make
install    : |
    %make_install
