name       : ffmpeg
homepage   : https://www.ffmpeg.org/
version    : 2.8.1
release    : 7
source     :
    - http://ffmpeg.org/releases/ffmpeg-2.8.1.tar.xz : 5790162028a868234f4f60b030f5f51bd70785de8a27878e271df029cdf4cb9a
license    : LGPL-2.0
summary    : A complete, cross-platform solution to record, convert and stream audio and video.
description: |
    A complete, cross-platform solution to record, convert and stream audio and video.
builddeps  :
    - pkgconfig(x264)
    - pkgconfig(vdpau)
    - pkgconfig(freetype2)
    - pkgconfig(ogg)
    - pkgconfig(openssl)
    - pkgconfig(gnutls)
    - pkgconfig(theora)
    - pkgconfig(x11)
    - pkgconfig(vpx)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
setup      : |
    # Revisit to enable All The Things
    ./configure --prefix=/usr \
        --libdir=%libdir% \
        --enable-shared \
        --disable-static \
        --enable-libx264 \
        --enable-libtheora \
        --enable-libfreetype \
        --enable-gpl \
        --enable-x11grab \
        --enable-libvpx \
        --enable-vdpau \
        --enable-opengl \
        --enable-nonfree \
        --enable-openssl \
        --enable-gnutls
build      : |
    %make
install    : |
    %make_install
