name       : ffmpeg
homepage   : https://www.ffmpeg.org/
version    : 4.1.2
release    : 65
source     :
    - https://ffmpeg.org/releases/ffmpeg-4.1.2.tar.xz : b95f0ae44798ab1434155ac7f81f30a7e9760a02282e4b5898372c22a335347b
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : A complete, cross-platform solution to record, convert and stream audio
    and video.
description: |
    FFmpeg is a multimedia framework, able to decode, encode, transcode, mux, demux,
    stream, filter and play several formats that humans and machines have created.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aom)
    - pkgconfig(caca)
    - pkgconfig(fdk-aac)
    - pkgconfig(ffnvcodec)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(openssl)
    - pkgconfig(opus)
    - pkgconfig(sdl2)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - pkgconfig(zimg)
    - bzip2-devel
    - lame-devel
    - libgcrypt-devel
    - snappy-devel
    - xvidcore-devel
patterns   :
    - devel : [/usr/share/man/man3*]
setup      : |
    ./configure --prefix=/usr \
        --libdir=%libdir% \
        --disable-debug \
        --disable-stripping \
        --enable-shared \
        --disable-static \
        --enable-avisynth \
        --enable-avresample \
        --enable-gcrypt \
        --enable-gpl \
        --enable-libaom \
        --enable-libass \
        --enable-libbluray \
        --enable-libcaca \
        --enable-libcdio \
        --enable-libfdk-aac \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libfribidi \
        --enable-libmp3lame \
        --enable-libopus \
        --enable-libpulse \
        --enable-libsnappy \
        --enable-libspeex \
        --enable-libssh \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libv4l2 \
        --enable-libvorbis \
        --enable-libvpx \
        --enable-libwebp \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxvid \
        --enable-libzimg \
        --enable-nonfree \
        --enable-nvdec \
        --enable-nvenc \
        --enable-openal \
        --enable-opengl \
        --enable-openssl \
        --enable-sdl2 \
        --enable-version3
build      : |
    %make
install    : |
    %make_install
